var dir_67fbc96c1612ec9308aa45448622937d =
[
    [ "art.c", "art_8c.html", "art_8c" ],
    [ "attention.c", "attention_8c.html", "attention_8c" ],
    [ "captcha.c", "captcha_8c.html", "captcha_8c" ],
    [ "cifar.c", "cifar_8c.html", "cifar_8c" ],
    [ "classifier.c", "classifier_8c.html", "classifier_8c" ],
    [ "coco.c", "coco_8c.html", "coco_8c" ],
    [ "darknet.c", "darknet_8c.html", "darknet_8c" ],
    [ "detector-scipy-opencv.py", "detector-scipy-opencv_8py.html", "detector-scipy-opencv_8py" ],
    [ "detector.c", "detector_8c.html", "detector_8c" ],
    [ "detector.py", "detector_8py.html", "detector_8py" ],
    [ "dice.c", "dice_8c.html", "dice_8c" ],
    [ "go.c", "go_8c.html", "go_8c" ],
    [ "lsd.c", "lsd_8c.html", "lsd_8c" ],
    [ "nightmare.c", "nightmare_8c.html", "nightmare_8c" ],
    [ "regressor.c", "regressor_8c.html", "regressor_8c" ],
    [ "rnn.c", "rnn_8c.html", "rnn_8c" ],
    [ "rnn_vid.c", "rnn__vid_8c.html", "rnn__vid_8c" ],
    [ "segmenter.c", "segmenter_8c.html", "segmenter_8c" ],
    [ "super.c", "super_8c.html", "super_8c" ],
    [ "swag.c", "swag_8c.html", "swag_8c" ],
    [ "tag.c", "tag_8c.html", "tag_8c" ],
    [ "voxel.c", "voxel_8c.html", "voxel_8c" ],
    [ "writing.c", "writing_8c.html", "writing_8c" ],
    [ "yolo.c", "yolo_8c.html", "yolo_8c" ]
];